version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: temo-website-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: asdf
      POSTGRES_DB: temo-website
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
