export const products = [
  {
    id: "1",
    name: "Max Men's Half Sleeves Regular Fit Crew Neck T-Shirt",
    price: 179.10,
    images: [
      "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3",
      "https://images.unsplash.com/photo-1583743814966-8936f5b7be1a?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3"
    ],
    discount: 0.10,
    category: "fashion",
  },
  {
    id: "2",
    name: "Vivel Body Wash, Glycerin and Honey, Moisturizing",
    price: 89.10,
    images: [
      "https://images.unsplash.com/photo-1556228720-195a672e8a03?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3",
      "https://images.unsplash.com/photo-1631729371254-42c2892f0e6e?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3"
    ],
    discount: 0.10,
    category: "beauty",
  },
  {
    id: "3",
    name: "SOFTSPUN Microfiber Cloth- 4 pcs - 40x40 cms",
    price: 99.50,
    images: [
      "https://images.unsplash.com/photo-1563453392212-326f5e854473?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3",
      "https://images.unsplash.com/photo-1583947215259-38e31be8751f?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3"
    ],
    discount: 0.50,
    category: "home",
  },
  {
    id: "4",
    name: "Boult Audio Newly Launched Z20 Pro Earbuds",
    price: 599.90,
    images: [
      "https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3",
      "https://images.unsplash.com/photo-1608156639585-b3a032ef9689?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3"
    ],
    discount: 0.90,
    category: "electronics",
  },
  {
    id: "5",
    name: "ShineXPro 200mL Windshield Washer Fluid",
    price: 149.50,
    images: [
      "https://images.unsplash.com/photo-1441148345475-03a2e82f9719?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3",
      "https://images.unsplash.com/photo-1487754180451-c456f719a1fc?w=500&auto=format&fit=crop&q=60&ixlib=rb-4.0.3"
    ],
    discount: 0.50,
    category: "automotive",
  },
]

export const categories = [
  {
    id: "electronics",
    name: "Electronics",
    icon: "laptop",
  },
  {
    id: "home",
    name: "Home & Kitchen",
    icon: "home",
  },
  {
    id: "fashion",
    name: "Netflixn Fashion",
    icon: "shirt",
  },
  {
    id: "computers",
    name: "Computers",
    icon: "monitor",
  },
  {
    id: "automotive",
    name: "Car & Motorbike",
    icon: "car",
  },
  {
    id: "beauty",
    name: "Beauty & Personal Care",
    icon: "sparkles",
  },
  {
    id: "sports",
    name: "Sports, Fitness & Outdoors",
    icon: "dumbbell",
  },
]

export const productReviews = [
  {
    category: "electronics",
    reviews: [
      { rating: 4, comment: "Great sound quality.", author: "John Doe", date: "2024-03-01", verified: true },
      { rating: 5, comment: "Very durable and reliable.", author: "Jane Smith", date: "2024-03-02", verified: true },
      { rating: 3, comment: "Good, but a bit overpriced.", author: "Alice Johnson", date: "2024-03-03", verified: false },
      { rating: 4, comment: "Perfect for daily use.", author: "Chris Lee", date: "2024-03-04", verified: true },
      { rating: 5, comment: "Exceeded my expectations!", author: "Emma Brown", date: "2024-03-05", verified: true },
      { rating: 3, comment: "Average performance.", author: "Michael Green", date: "2024-03-06", verified: false },
      { rating: 4, comment: "Good build quality.", author: "Olivia Wilson", date: "2024-03-07", verified: true },
      { rating: 5, comment: "Highly recommend it!", author: "Ethan White", date: "2024-03-08", verified: true },
      { rating: 3, comment: "Works fine but heats up.", author: "Sophia Moore", date: "2024-03-09", verified: false },
      { rating: 4, comment: "Stylish and functional.", author: "Noah Garcia", date: "2024-03-10", verified: true },
      { rating: 5, comment: "Battery life is amazing.", author: "Liam Miller", date: "2024-03-11", verified: true },
      { rating: 4, comment: "Compact and easy to use.", author: "Mia Davis", date: "2024-03-12", verified: true },
      { rating: 3, comment: "Not compatible with my devices.", author: "Ella Martinez", date: "2024-03-13", verified: false },
      { rating: 4, comment: "Good value for money.", author: "Oliver Clark", date: "2024-03-14", verified: true },
      { rating: 5, comment: "Picture quality is outstanding.", author: "Ava Hernandez", date: "2024-03-15", verified: true },
      { rating: 3, comment: "Took time to set up.", author: "Lucas Lopez", date: "2024-03-16", verified: false },
      { rating: 4, comment: "Perfect for gaming.", author: "Charlotte Harris", date: "2024-03-17", verified: true },
      { rating: 5, comment: "Super fast and responsive.", author: "James Walker", date: "2024-03-18", verified: true },
      { rating: 3, comment: "Build feels flimsy.", author: "Amelia Young", date: "2024-03-19", verified: false },
      { rating: 4, comment: "Great for streaming videos.", author: "Harper King", date: "2024-03-20", verified: true },
      { rating: 5, comment: "Very user-friendly.", author: "Henry Carter", date: "2024-03-21", verified: true },
      { rating: 4, comment: "Clear and sharp display.", author: "Evelyn Wright", date: "2024-03-22", verified: true },
      { rating: 3, comment: "Doesn’t work well outdoors.", author: "Benjamin Scott", date: "2024-03-23", verified: false },
      { rating: 4, comment: "Perfect size for travel.", author: "Zoe Adams", date: "2024-03-24", verified: true },
      { rating: 5, comment: "Reliable and sturdy design.", author: "Daniel Turner", date: "2024-03-25", verified: true },
      { rating: 3, comment: "Frequent software updates required.", author: "Sophia Hall", date: "2024-03-26", verified: false },
      { rating: 4, comment: "Great features for the price.", author: "Jack Allen", date: "2024-03-27", verified: true },
      { rating: 5, comment: "Very lightweight and portable.", author: "Lily Evans", date: "2024-03-28", verified: true },
      { rating: 3, comment: "Buttons feel unresponsive.", author: "Ryan Mitchell", date: "2024-03-29", verified: false },
      { rating: 4, comment: "Setup was quick and easy.", author: "Grace Baker", date: "2024-03-30", verified: true },
      { rating: 5, comment: "The sound is crystal clear.", author: "Elijah Rivera", date: "2024-03-31", verified: true },
      { rating: 4, comment: "Charges very quickly.", author: "Emily Perez", date: "2024-04-01", verified: true },
      { rating: 3, comment: "Feels bulky to carry around.", author: "Hannah Brooks", date: "2024-04-02", verified: false },
      { rating: 4, comment: "Perfect for my office work.", author: "Nathan Ross", date: "2024-04-03", verified: true },
      { rating: 5, comment: "Works seamlessly with my phone.", author: "Isabella Foster", date: "2024-04-04", verified: true },
      { rating: 3, comment: "Not as durable as expected.", author: "Samuel Jenkins", date: "2024-04-05", verified: false },
      { rating: 4, comment: "Compact but powerful.", author: "Victoria Barnes", date: "2024-04-06", verified: true },
      { rating: 5, comment: "Exceeded my expectations.", author: "Matthew Bryant", date: "2024-04-07", verified: true },
      { rating: 3, comment: "Tends to overheat.", author: "Scarlett Rivera", date: "2024-04-08", verified: false },
      { rating: 4, comment: "Great design and functionality.", author: "Leo Carter", date: "2024-04-09", verified: true }
    ]
  },
  {
    category: "home",
    reviews: [
      { rating: 5, comment: "Perfect for my living room!", author: "John Doe", date: "2024-03-01", verified: true },
      { rating: 4, comment: "Very sturdy and well-built.", author: "Jane Smith", date: "2024-03-02", verified: true },
      { rating: 3, comment: "Not the size I expected.", author: "Alice Johnson", date: "2024-03-03", verified: false },
      { rating: 4, comment: "Adds a modern touch to my home.", author: "Chris Lee", date: "2024-03-04", verified: true },
      { rating: 5, comment: "Quality exceeds the price!", author: "Emma Brown", date: "2024-03-05", verified: true },
      { rating: 3, comment: "Assembly instructions were confusing.", author: "Michael Green", date: "2024-03-06", verified: false },
      { rating: 4, comment: "Blends well with my decor.", author: "Olivia Wilson", date: "2024-03-07", verified: true },
      { rating: 5, comment: "Exactly as pictured.", author: "Ethan White", date: "2024-03-08", verified: true },
      { rating: 3, comment: "Color was slightly off.", author: "Sophia Moore", date: "2024-03-09", verified: false },
      { rating: 4, comment: "Good value for money.", author: "Noah Garcia", date: "2024-03-10", verified: true },
      { rating: 5, comment: "Looks great and feels durable.", author: "Liam Miller", date: "2024-03-11", verified: true },
      { rating: 4, comment: "Easy to clean and maintain.", author: "Mia Davis", date: "2024-03-12", verified: true },
      { rating: 3, comment: "The finish isn’t smooth.", author: "Ella Martinez", date: "2024-03-13", verified: false },
      { rating: 4, comment: "Perfect for small spaces.", author: "Oliver Clark", date: "2024-03-14", verified: true },
      { rating: 5, comment: "Feels premium and high-quality.", author: "Ava Hernandez", date: "2024-03-15", verified: true },
      { rating: 3, comment: "Took longer than expected to arrive.", author: "Lucas Lopez", date: "2024-03-16", verified: false },
      { rating: 4, comment: "Well-packaged and arrived safely.", author: "Charlotte Harris", date: "2024-03-17", verified: true },
      { rating: 5, comment: "Looks beautiful in my bedroom.", author: "James Walker", date: "2024-03-18", verified: true },
      { rating: 3, comment: "Edges were slightly damaged.", author: "Amelia Young", date: "2024-03-19", verified: false },
      { rating: 4, comment: "Good build quality for the price.", author: "Harper King", date: "2024-03-20", verified: true },
      { rating: 5, comment: "Exceeded my expectations!", author: "Henry Carter", date: "2024-03-21", verified: true },
      { rating: 4, comment: "Blends well with other furniture.", author: "Evelyn Wright", date: "2024-03-22", verified: true },
      { rating: 3, comment: "Not as sturdy as I hoped.", author: "Benjamin Scott", date: "2024-03-23", verified: false },
      { rating: 4, comment: "Perfect size for my kitchen.", author: "Zoe Adams", date: "2024-03-24", verified: true },
      { rating: 5, comment: "Stylish and functional.", author: "Daniel Turner", date: "2024-03-25", verified: true },
      { rating: 3, comment: "Some screws were missing.", author: "Sophia Hall", date: "2024-03-26", verified: false },
      { rating: 4, comment: "Looks exactly as advertised.", author: "Jack Allen", date: "2024-03-27", verified: true },
      { rating: 5, comment: "Perfect for my workspace.", author: "Lily Evans", date: "2024-03-28", verified: true },
      { rating: 3, comment: "The finish could be better.", author: "Ryan Mitchell", date: "2024-03-29", verified: false },
      { rating: 4, comment: "Assembly was very simple.", author: "Grace Baker", date: "2024-03-30", verified: true },
      { rating: 5, comment: "Feels very sturdy and well-built.", author: "Elijah Rivera", date: "2024-03-31", verified: true },
      { rating: 4, comment: "Matches perfectly with my decor.", author: "Emily Perez", date: "2024-04-01", verified: true },
      { rating: 3, comment: "Corners were slightly bent.", author: "Hannah Brooks", date: "2024-04-02", verified: false },
      { rating: 4, comment: "Great for organizing small items.", author: "Nathan Ross", date: "2024-04-03", verified: true },
      { rating: 5, comment: "Super easy to clean.", author: "Isabella Foster", date: "2024-04-04", verified: true },
      { rating: 3, comment: "Paint chipped after a few uses.", author: "Samuel Jenkins", date: "2024-04-05", verified: false },
      { rating: 4, comment: "Compact and functional.", author: "Victoria Barnes", date: "2024-04-06", verified: true },
      { rating: 5, comment: "Looks amazing in my entryway.", author: "Matthew Bryant", date: "2024-04-07", verified: true },
      { rating: 3, comment: "Not worth the price.", author: "Scarlett Rivera", date: "2024-04-08", verified: false },
      { rating: 4, comment: "Great product for small homes.", author: "Leo Carter", date: "2024-04-09", verified: true },
      { rating: 5, comment: "Feels very premium and well-designed.", author: "Mia Walker", date: "2024-04-10", verified: true },
      { rating: 3, comment: "Not as described in the details.", author: "Evan Morgan", date: "2024-04-11", verified: false },
      { rating: 4, comment: "Very sturdy and durable.", author: "Ava Hill", date: "2024-04-12", verified: true },
      { rating: 5, comment: "Absolutely love it!", author: "Lucas Thompson", date: "2024-04-13", verified: true }
    ]
  },
  {
    category: "fashion",
    reviews: [
      { rating: 5, comment: "Fits perfectly and looks amazing!", author: "Sophia Brown", date: "2024-03-01", verified: true },
      { rating: 4, comment: "Very stylish and trendy.", author: "Liam Johnson", date: "2024-03-02", verified: true },
      { rating: 3, comment: "Fabric feels a bit rough.", author: "Emily Davis", date: "2024-03-03", verified: false },
      { rating: 5, comment: "The material is of excellent quality.", author: "James Miller", date: "2024-03-04", verified: true },
      { rating: 4, comment: "Great for casual outings.", author: "Olivia Wilson", date: "2024-03-05", verified: true },
      { rating: 3, comment: "Size runs smaller than expected.", author: "Mason Taylor", date: "2024-03-06", verified: false },
      { rating: 4, comment: "Looks exactly as advertised.", author: "Isabella Martinez", date: "2024-03-07", verified: true },
      { rating: 5, comment: "Very comfortable to wear.", author: "Ethan Anderson", date: "2024-03-08", verified: true },
      { rating: 3, comment: "Color fades after washing.", author: "Charlotte Moore", date: "2024-03-09", verified: false },
      { rating: 4, comment: "Lightweight and breathable fabric.", author: "Noah Garcia", date: "2024-03-10", verified: true },
      { rating: 5, comment: "Perfect for special occasions.", author: "Ava Lee", date: "2024-03-11", verified: true },
      { rating: 4, comment: "Matches well with accessories.", author: "Lucas Thompson", date: "2024-03-12", verified: true },
      { rating: 3, comment: "A bit overpriced for the quality.", author: "Mia Rodriguez", date: "2024-03-13", verified: false },
      { rating: 4, comment: "Easy to wash and maintain.", author: "Elijah Hernandez", date: "2024-03-14", verified: true },
      { rating: 5, comment: "Highly recommend it for anyone!", author: "Ella Clark", date: "2024-03-15", verified: true },
      { rating: 3, comment: "Fabric shrinks after the first wash.", author: "William Perez", date: "2024-03-16", verified: false },
      { rating: 4, comment: "Simple yet elegant design.", author: "Amelia Adams", date: "2024-03-17", verified: true },
      { rating: 5, comment: "Feels very luxurious.", author: "Henry Turner", date: "2024-03-18", verified: true },
      { rating: 3, comment: "The stitching came undone.", author: "Zoe Hill", date: "2024-03-19", verified: false },
      { rating: 4, comment: "Great fit for all body types.", author: "Benjamin Lewis", date: "2024-03-20", verified: true },
      { rating: 5, comment: "Got lots of compliments!", author: "Harper Walker", date: "2024-03-21", verified: true },
      { rating: 4, comment: "Goes well with my wardrobe.", author: "Daniel Allen", date: "2024-03-22", verified: true },
      { rating: 3, comment: "A bit tight around the shoulders.", author: "Scarlett Young", date: "2024-03-23", verified: false },
      { rating: 4, comment: "Perfect for summer wear.", author: "Leo King", date: "2024-03-24", verified: true },
      { rating: 5, comment: "Super soft and comfortable.", author: "Victoria Wright", date: "2024-03-25", verified: true },
      { rating: 3, comment: "The color was not as shown.", author: "Jack Scott", date: "2024-03-26", verified: false },
      { rating: 4, comment: "Good stitching and craftsmanship.", author: "Grace Lopez", date: "2024-03-27", verified: true },
      { rating: 5, comment: "Exceeded my expectations!", author: "Nathan Harris", date: "2024-03-28", verified: true },
      { rating: 3, comment: "Felt uncomfortable after long wear.", author: "Chloe Walker", date: "2024-03-29", verified: false },
      { rating: 4, comment: "Great for layering.", author: "Evelyn Baker", date: "2024-03-30", verified: true },
      { rating: 5, comment: "Very trendy and unique design.", author: "Liam Gonzalez", date: "2024-03-31", verified: true },
      { rating: 4, comment: "The fabric feels soft to the touch.", author: "Aubrey Carter", date: "2024-04-01", verified: true },
      { rating: 3, comment: "Not durable for daily use.", author: "Ryan Rivera", date: "2024-04-02", verified: false },
      { rating: 4, comment: "Pairs well with my favorite jeans.", author: "Emily Brooks", date: "2024-04-03", verified: true },
      { rating: 5, comment: "Feels very high-end.", author: "Samuel Jenkins", date: "2024-04-04", verified: true },
      { rating: 3, comment: "Color bled during washing.", author: "Ella Sanders", date: "2024-04-05", verified: false },
      { rating: 4, comment: "Perfect length for dresses.", author: "Scarlett Price", date: "2024-04-06", verified: true },
      { rating: 5, comment: "Very flattering fit.", author: "Nathan Ward", date: "2024-04-07", verified: true },
      { rating: 3, comment: "Material feels scratchy.", author: "Lila Barnes", date: "2024-04-08", verified: false },
      { rating: 4, comment: "Light and breezy for summer.", author: "Evelyn Torres", date: "2024-04-09", verified: true },
      { rating: 5, comment: "Absolutely love the design!", author: "Mason Powell", date: "2024-04-10", verified: true },
      { rating: 4, comment: "Good for both casual and formal wear.", author: "Sophia Reed", date: "2024-04-11", verified: true },
      { rating: 3, comment: "The zipper broke after a week.", author: "Oliver Patterson", date: "2024-04-12", verified: false },
      { rating: 4, comment: "Nice addition to my wardrobe.", author: "Zoe Hughes", date: "2024-04-13", verified: true },
      { rating: 5, comment: "Perfect for everyday wear.", author: "Amelia Flores", date: "2024-04-14", verified: true }
    ]
  },
  {
    category: "automotive",
    reviews: [
      { rating: 5, comment: "Very durable and reliable.", author: "John Carter", date: "2024-03-01", verified: true },
      { rating: 4, comment: "Perfect fit for my car.", author: "Sarah Johnson", date: "2024-03-02", verified: true },
      { rating: 3, comment: "The material feels a bit flimsy.", author: "Ethan Brown", date: "2024-03-03", verified: false },
      { rating: 4, comment: "Great value for the price.", author: "Emma Davis", date: "2024-03-04", verified: true },
      { rating: 5, comment: "Exceeded my expectations.", author: "Lucas Green", date: "2024-03-05", verified: true },
      { rating: 3, comment: "Took some effort to install.", author: "Olivia White", date: "2024-03-06", verified: false },
      { rating: 4, comment: "Looks great and feels sturdy.", author: "Liam Martinez", date: "2024-03-07", verified: true },
      { rating: 5, comment: "Highly recommend this product.", author: "Sophia Taylor", date: "2024-03-08", verified: true },
      { rating: 3, comment: "Doesn’t fit as advertised.", author: "Noah Wilson", date: "2024-03-09", verified: false },
      { rating: 4, comment: "Very easy to clean.", author: "Ava Harris", date: "2024-03-10", verified: true },
      { rating: 5, comment: "Perfect for long drives.", author: "Henry Clark", date: "2024-03-11", verified: true },
      { rating: 4, comment: "Works as described.", author: "Mia Young", date: "2024-03-12", verified: true },
      { rating: 3, comment: "The quality could be better.", author: "Elijah Lee", date: "2024-03-13", verified: false },
      { rating: 4, comment: "Very functional and sturdy.", author: "Charlotte Walker", date: "2024-03-14", verified: true },
      { rating: 5, comment: "Amazing product for the price.", author: "James Perez", date: "2024-03-15", verified: true },
      { rating: 3, comment: "Doesn’t match my car's interior.", author: "Amelia Adams", date: "2024-03-16", verified: false },
      { rating: 4, comment: "Perfect size and fit.", author: "Oliver King", date: "2024-03-17", verified: true },
      { rating: 5, comment: "Very easy to install.", author: "Zoe Wright", date: "2024-03-18", verified: true },
      { rating: 3, comment: "Couldn’t get it to work.", author: "Benjamin Allen", date: "2024-03-19", verified: false },
      { rating: 4, comment: "Feels very durable.", author: "Harper Torres", date: "2024-03-20", verified: true },
      { rating: 5, comment: "Looks great and works perfectly.", author: "Nathan Flores", date: "2024-03-21", verified: true },
      { rating: 4, comment: "Highly functional and efficient.", author: "Scarlett Rivera", date: "2024-03-22", verified: true },
      { rating: 3, comment: "The instructions were unclear.", author: "Leo Brooks", date: "2024-03-23", verified: false },
      { rating: 4, comment: "Good value for the money.", author: "Victoria Hall", date: "2024-03-24", verified: true },
      { rating: 5, comment: "I love how it enhances my car.", author: "Daniel Scott", date: "2024-03-25", verified: true },
      { rating: 3, comment: "Not as durable as expected.", author: "Chloe Mitchell", date: "2024-03-26", verified: false },
      { rating: 4, comment: "Great for organizing my tools.", author: "Evelyn Baker", date: "2024-03-27", verified: true },
      { rating: 5, comment: "Perfect for road trips!", author: "Jack Jenkins", date: "2024-03-28", verified: true },
      { rating: 3, comment: "Paint chipped easily.", author: "Ryan Sanders", date: "2024-03-29", verified: false },
      { rating: 4, comment: "Fits my car like a glove.", author: "Emily Price", date: "2024-03-30", verified: true },
      { rating: 5, comment: "Very user-friendly product.", author: "Samuel Torres", date: "2024-03-31", verified: true },
      { rating: 4, comment: "Great quality for everyday use.", author: "Sophia Moore", date: "2024-04-01", verified: true },
      { rating: 3, comment: "A bit expensive for what it offers.", author: "Noah Barnes", date: "2024-04-02", verified: false },
      { rating: 4, comment: "Solid build and good design.", author: "Charlotte Hughes", date: "2024-04-03", verified: true },
      { rating: 5, comment: "Makes driving much easier.", author: "Liam Brooks", date: "2024-04-04", verified: true },
      { rating: 3, comment: "Hard to install properly.", author: "Zoe Reed", date: "2024-04-05", verified: false },
      { rating: 4, comment: "Looks great in my car.", author: "Benjamin Jenkins", date: "2024-04-06", verified: true },
      { rating: 5, comment: "Extremely useful for car maintenance.", author: "Ava Foster", date: "2024-04-07", verified: true },
      { rating: 3, comment: "Not compatible with my car model.", author: "Henry Bryant", date: "2024-04-08", verified: false },
      { rating: 4, comment: "Very practical and useful.", author: "Mia Barnes", date: "2024-04-09", verified: true },
      { rating: 5, comment: "Highly recommended for car enthusiasts.", author: "Ethan Price", date: "2024-04-10", verified: true },
      { rating: 4, comment: "Great for long-term use.", author: "Lucas Adams", date: "2024-04-11", verified: true },
      { rating: 3, comment: "Arrived with minor scratches.", author: "Ella Clark", date: "2024-04-12", verified: false },
      { rating: 4, comment: "Blends perfectly with my interior.", author: "Nathan Lewis", date: "2024-04-13", verified: true },
      { rating: 5, comment: "Superb quality and performance.", author: "Emma Hill", date: "2024-04-14", verified: true }
    ]
  },
  {
    category: "beauty",
    reviews: [
      { rating: 5, comment: "Leaves my skin feeling soft and refreshed.", author: "Sophia Brown", date: "2024-03-01", verified: true },
      { rating: 4, comment: "Great product for daily use.", author: "Emma Davis", date: "2024-03-02", verified: true },
      { rating: 3, comment: "The scent is a bit strong for me.", author: "Ava Taylor", date: "2024-03-03", verified: false },
      { rating: 5, comment: "Perfect for my sensitive skin.", author: "Mia Johnson", date: "2024-03-04", verified: true },
      { rating: 4, comment: "Moisturizes well without feeling greasy.", author: "Olivia Martinez", date: "2024-03-05", verified: true },
      { rating: 3, comment: "Takes time to show results.", author: "Isabella Wilson", date: "2024-03-06", verified: false },
      { rating: 5, comment: "Highly recommend for anyone!", author: "Charlotte Moore", date: "2024-03-07", verified: true },
      { rating: 4, comment: "Gentle and effective on my skin.", author: "Amelia White", date: "2024-03-08", verified: true },
      { rating: 3, comment: "Did not suit my skin type.", author: "Ella Harris", date: "2024-03-09", verified: false },
      { rating: 5, comment: "Feels luxurious and works wonders.", author: "Harper Green", date: "2024-03-10", verified: true },
      { rating: 4, comment: "Good value for the price.", author: "Zoe Brown", date: "2024-03-11", verified: true },
      { rating: 5, comment: "Smells amazing and lasts all day.", author: "Liam Clark", date: "2024-03-12", verified: true },
      { rating: 3, comment: "The packaging could be better.", author: "Benjamin Wright", date: "2024-03-13", verified: false },
      { rating: 4, comment: "Light and non-greasy formula.", author: "Evelyn King", date: "2024-03-14", verified: true },
      { rating: 5, comment: "My go-to beauty product!", author: "Scarlett Lee", date: "2024-03-15", verified: true },
      { rating: 3, comment: "Not as effective as I expected.", author: "Avery Adams", date: "2024-03-16", verified: false },
      { rating: 4, comment: "Works well for everyday use.", author: "Sofia Brooks", date: "2024-03-17", verified: true },
      { rating: 5, comment: "Feels very premium and worth the price.", author: "Eleanor Torres", date: "2024-03-18", verified: true },
      { rating: 3, comment: "The product was slightly damaged on arrival.", author: "Chloe Rivera", date: "2024-03-19", verified: false },
      { rating: 4, comment: "Gives a natural glow to the skin.", author: "Victoria Jenkins", date: "2024-03-20", verified: true },
      { rating: 5, comment: "Absolutely love this product!", author: "Hannah Flores", date: "2024-03-21", verified: true },
      { rating: 4, comment: "Very soothing and gentle.", author: "Lila Foster", date: "2024-03-22", verified: true },
      { rating: 3, comment: "Not suitable for oily skin.", author: "Eleanor Bryant", date: "2024-03-23", verified: false },
      { rating: 4, comment: "Absorbs quickly and feels light.", author: "Chloe Lewis", date: "2024-03-24", verified: true },
      { rating: 5, comment: "Works like magic on dry skin.", author: "Ella Walker", date: "2024-03-25", verified: true },
      { rating: 3, comment: "Did not work well for me.", author: "Avery Hall", date: "2024-03-26", verified: false },
      { rating: 4, comment: "Perfect for my nighttime routine.", author: "Isla Sanders", date: "2024-03-27", verified: true },
      { rating: 5, comment: "Keeps my skin hydrated all day.", author: "Liam Brooks", date: "2024-03-28", verified: true },
      { rating: 3, comment: "Caused mild irritation.", author: "Benjamin Carter", date: "2024-03-29", verified: false },
      { rating: 4, comment: "Lightweight and refreshing.", author: "Sophia Gonzalez", date: "2024-03-30", verified: true },
      { rating: 5, comment: "My skin feels so smooth!", author: "Ava Price", date: "2024-03-31", verified: true },
      { rating: 4, comment: "Perfect for sensitive skin.", author: "Lucas Turner", date: "2024-04-01", verified: true },
      { rating: 3, comment: "Not worth the hype.", author: "Emma Bell", date: "2024-04-02", verified: false },
      { rating: 4, comment: "Leaves a subtle glow.", author: "Elijah Scott", date: "2024-04-03", verified: true },
      { rating: 5, comment: "The best beauty product I've used!", author: "Sophia Hill", date: "2024-04-04", verified: true },
      { rating: 3, comment: "A bit greasy for my liking.", author: "Noah Jenkins", date: "2024-04-05", verified: false },
      { rating: 4, comment: "Very hydrating and lightweight.", author: "Ava Carter", date: "2024-04-06", verified: true },
      { rating: 5, comment: "Love how my skin feels after use.", author: "Mason Evans", date: "2024-04-07", verified: true },
      { rating: 3, comment: "The scent is overpowering.", author: "Ethan Reed", date: "2024-04-08", verified: false },
      { rating: 4, comment: "Gives my skin a soft texture.", author: "Mia Torres", date: "2024-04-09", verified: true },
      { rating: 5, comment: "Perfect for dry and sensitive skin.", author: "Scarlett Adams", date: "2024-04-10", verified: true },
      { rating: 4, comment: "Very effective for dark spots.", author: "Isabella Mitchell", date: "2024-04-11", verified: true },
      { rating: 3, comment: "Takes time to show results.", author: "Lucas Gonzalez", date: "2024-04-12", verified: false },
      { rating: 5, comment: "Instantly brightens my skin!", author: "Olivia Brooks", date: "2024-04-13", verified: true },
      { rating: 4, comment: "Feels natural and gentle.", author: "Charlotte Rivera", date: "2024-04-14", verified: true }
    ]
  },
  {
    category: "sports",
    reviews: [
      { rating: 5, comment: "Great quality, perfect for my workouts.", author: "Ethan Johnson", date: "2024-03-01", verified: true },
      { rating: 4, comment: "Very durable and lightweight.", author: "Mia Davis", date: "2024-03-02", verified: true },
      { rating: 3, comment: "Not as comfortable as I expected.", author: "Noah Brown", date: "2024-03-03", verified: false },
      { rating: 5, comment: "Perfect for outdoor activities.", author: "Emma Wilson", date: "2024-03-04", verified: true },
      { rating: 4, comment: "Great grip and control.", author: "Sophia Martinez", date: "2024-03-05", verified: true },
      { rating: 3, comment: "Feels a bit heavy during use.", author: "Liam White", date: "2024-03-06", verified: false },
      { rating: 5, comment: "Improved my performance significantly.", author: "Charlotte Moore", date: "2024-03-07", verified: true },
      { rating: 4, comment: "Good for both beginners and pros.", author: "Lucas Garcia", date: "2024-03-08", verified: true },
      { rating: 3, comment: "Material started wearing out quickly.", author: "Isabella Taylor", date: "2024-03-09", verified: false },
      { rating: 5, comment: "Provides excellent support.", author: "Henry Harris", date: "2024-03-10", verified: true },
      { rating: 4, comment: "Very easy to use and adjust.", author: "Harper King", date: "2024-03-11", verified: true },
      { rating: 3, comment: "Too bulky for my liking.", author: "Evelyn Adams", date: "2024-03-12", verified: false },
      { rating: 5, comment: "Perfect for daily training.", author: "Liam Carter", date: "2024-03-13", verified: true },
      { rating: 4, comment: "Great addition to my sports gear.", author: "Sophia Rivera", date: "2024-03-14", verified: true },
      { rating: 3, comment: "The size didn’t fit me well.", author: "Benjamin Scott", date: "2024-03-15", verified: false },
      { rating: 5, comment: "Highly recommend for athletes.", author: "Ava Lopez", date: "2024-03-16", verified: true },
      { rating: 4, comment: "Good balance and flexibility.", author: "Mason Lewis", date: "2024-03-17", verified: true },
      { rating: 3, comment: "The stitching came undone.", author: "Elijah Hill", date: "2024-03-18", verified: false },
      { rating: 5, comment: "Helps me push my limits.", author: "Olivia Walker", date: "2024-03-19", verified: true },
      { rating: 4, comment: "Durable and comfortable for long use.", author: "Nathan Brooks", date: "2024-03-20", verified: true },
      { rating: 5, comment: "Gives great support and protection.", author: "Scarlett Price", date: "2024-03-21", verified: true },
      { rating: 4, comment: "Perfect for outdoor adventures.", author: "Eleanor Turner", date: "2024-03-22", verified: true },
      { rating: 3, comment: "Didn’t perform as expected.", author: "Ryan Foster", date: "2024-03-23", verified: false },
      { rating: 4, comment: "Great for building strength.", author: "Grace Perez", date: "2024-03-24", verified: true },
      { rating: 5, comment: "My go-to for all sports activities.", author: "Lucas Hall", date: "2024-03-25", verified: true },
      { rating: 3, comment: "The grip wasn’t strong enough.", author: "Ella Jenkins", date: "2024-03-26", verified: false },
      { rating: 4, comment: "Easy to carry and store.", author: "Zoe Mitchell", date: "2024-03-27", verified: true },
      { rating: 5, comment: "Great for improving technique.", author: "Ethan Sanders", date: "2024-03-28", verified: true },
      { rating: 3, comment: "The color started fading.", author: "Amelia Gonzalez", date: "2024-03-29", verified: false },
      { rating: 4, comment: "Provides great stability.", author: "Isabella Ross", date: "2024-03-30", verified: true },
      { rating: 5, comment: "Perfectly designed for beginners.", author: "Henry Bell", date: "2024-03-31", verified: true },
      { rating: 4, comment: "Very versatile and durable.", author: "Mia Scott", date: "2024-04-01", verified: true },
      { rating: 3, comment: "Not suitable for intense activities.", author: "Harper Green", date: "2024-04-02", verified: false },
      { rating: 4, comment: "Affordable and effective.", author: "Elijah Turner", date: "2024-04-03", verified: true },
      { rating: 5, comment: "Very comfortable and breathable.", author: "Sophia Edwards", date: "2024-04-04", verified: true },
      { rating: 3, comment: "Didn’t meet my expectations.", author: "Noah Murphy", date: "2024-04-05", verified: false },
      { rating: 4, comment: "Perfect for recreational use.", author: "Liam Gonzalez", date: "2024-04-06", verified: true },
      { rating: 5, comment: "Made a noticeable difference in my training.", author: "Ella Rivera", date: "2024-04-07", verified: true },
      { rating: 3, comment: "Couldn’t withstand rough use.", author: "Lucas Young", date: "2024-04-08", verified: false },
      { rating: 4, comment: "Provides great traction.", author: "Ethan Adams", date: "2024-04-09", verified: true },
      { rating: 5, comment: "Perfect for high-performance training.", author: "Amelia Carter", date: "2024-04-10", verified: true },
      { rating: 4, comment: "Very lightweight and easy to use.", author: "Charlotte Moore", date: "2024-04-11", verified: true },
      { rating: 3, comment: "Not very durable over time.", author: "Nathan Hill", date: "2024-04-12", verified: false },
      { rating: 4, comment: "Great for stretching and warm-ups.", author: "Ava Wilson", date: "2024-04-13", verified: true },
      { rating: 5, comment: "My favorite sports gear so far!", author: "Isabella Wright", date: "2024-04-14", verified: true }
    ]
  },
  {
    category: "computers",
    reviews: [
      { rating: 5, comment: "Runs smoothly and handles multitasking well.", author: "John Smith", date: "2024-03-01", verified: true },
      { rating: 4, comment: "Good value for the price.", author: "Sophia Brown", date: "2024-03-02", verified: true },
      { rating: 3, comment: "Battery life could be better.", author: "Emma Johnson", date: "2024-03-03", verified: false },
      { rating: 5, comment: "Perfect for gaming and streaming.", author: "Liam Martinez", date: "2024-03-04", verified: true },
      { rating: 4, comment: "Compact and lightweight, easy to carry.", author: "Ava Taylor", date: "2024-03-05", verified: true },
      { rating: 3, comment: "Heats up quickly under heavy use.", author: "Ethan White", date: "2024-03-06", verified: false },
      { rating: 5, comment: "The display quality is outstanding.", author: "Mia Davis", date: "2024-03-07", verified: true },
      { rating: 4, comment: "Good for work and everyday tasks.", author: "Noah Wilson", date: "2024-03-08", verified: true },
      { rating: 3, comment: "Had issues with the keyboard.", author: "Olivia Moore", date: "2024-03-09", verified: false },
      { rating: 5, comment: "Great build quality and performance.", author: "Lucas Gonzalez", date: "2024-03-10", verified: true },
      { rating: 4, comment: "The speakers are clear and loud.", author: "Emily Wright", date: "2024-03-11", verified: true },
      { rating: 3, comment: "Limited ports for connectivity.", author: "James Scott", date: "2024-03-12", verified: false },
      { rating: 5, comment: "Handles video editing like a pro.", author: "Charlotte Adams", date: "2024-03-13", verified: true },
      { rating: 4, comment: "Good performance for office work.", author: "Evelyn Green", date: "2024-03-14", verified: true },
      { rating: 3, comment: "Fan noise is a bit loud.", author: "Henry King", date: "2024-03-15", verified: false },
      { rating: 5, comment: "Very fast boot-up time.", author: "Amelia Lewis", date: "2024-03-16", verified: true },
      { rating: 4, comment: "Keyboard is comfortable to type on.", author: "Zoe Brooks", date: "2024-03-17", verified: true },
      { rating: 3, comment: "The touchpad is not responsive enough.", author: "Elijah Rivera", date: "2024-03-18", verified: false },
      { rating: 5, comment: "Perfect for programming and coding.", author: "Sophia Hill", date: "2024-03-19", verified: true },
      { rating: 4, comment: "Reliable for everyday use.", author: "Nathan Harris", date: "2024-03-20", verified: true },
      { rating: 5, comment: "Handles 4K videos without a hitch.", author: "Scarlett Walker", date: "2024-03-21", verified: true },
      { rating: 4, comment: "Stylish design and good performance.", author: "Lucas Hall", date: "2024-03-22", verified: true },
      { rating: 3, comment: "Battery drains quickly under load.", author: "Ella Jenkins", date: "2024-03-23", verified: false },
      { rating: 4, comment: "Good for students and professionals.", author: "Benjamin Lopez", date: "2024-03-24", verified: true },
      { rating: 5, comment: "Exceeded my expectations!", author: "Harper Lewis", date: "2024-03-25", verified: true },
      { rating: 3, comment: "Occasional crashes while gaming.", author: "Grace Turner", date: "2024-03-26", verified: false },
      { rating: 4, comment: "The webcam quality is decent.", author: "Chloe Gonzalez", date: "2024-03-27", verified: true },
      { rating: 5, comment: "Perfect for remote work setups.", author: "Evelyn Bell", date: "2024-03-28", verified: true },
      { rating: 3, comment: "Not compatible with some accessories.", author: "Ryan Adams", date: "2024-03-29", verified: false },
      { rating: 4, comment: "Handles multitasking without issues.", author: "Liam Ross", date: "2024-03-30", verified: true },
      { rating: 5, comment: "Runs quietly and efficiently.", author: "Sophia Rivera", date: "2024-03-31", verified: true },
      { rating: 4, comment: "Build quality feels premium.", author: "Isabella Walker", date: "2024-04-01", verified: true },
      { rating: 3, comment: "Storage space is a bit limited.", author: "Henry Scott", date: "2024-04-02", verified: false },
      { rating: 4, comment: "Perfect for light gaming.", author: "Mia Harris", date: "2024-04-03", verified: true },
      { rating: 5, comment: "Excellent battery backup.", author: "Noah Brooks", date: "2024-04-04", verified: true },
      { rating: 3, comment: "Had issues with Wi-Fi connectivity.", author: "Olivia King", date: "2024-04-05", verified: false },
      { rating: 4, comment: "The screen resolution is amazing.", author: "Lucas Mitchell", date: "2024-04-06", verified: true },
      { rating: 5, comment: "Perfect for creative professionals.", author: "Ava Torres", date: "2024-04-07", verified: true },
      { rating: 3, comment: "Runs slow with heavy software.", author: "Liam Price", date: "2024-04-08", verified: false },
      { rating: 4, comment: "Feels solid and well-made.", author: "Scarlett Bell", date: "2024-04-09", verified: true },
      { rating: 5, comment: "Perfect for video conferences.", author: "Nathan Sanders", date: "2024-04-10", verified: true },
      { rating: 4, comment: "Great performance for the price.", author: "Harper Edwards", date: "2024-04-11", verified: true },
      { rating: 3, comment: "The fan gets loud at times.", author: "Grace Rivera", date: "2024-04-12", verified: false },
      { rating: 4, comment: "Good for work and play.", author: "Benjamin Gonzalez", date: "2024-04-13", verified: true },
      { rating: 5, comment: "Handles large projects with ease. ", author: "Chloe Green", date: "2024-04-14", verified: true }
    ]
  }
];
